ads-link: ""
new-forms-link: ""

telegram-bot-token: ""

publicidad:
  period: 900
  format: "&8[&7Publicidad&8] &b{message}"
  not-found: "&8[&7Publicidad&8] &bNo se ha encontrado ningún anuncio de {player}"
  usage: "&8[&7Publicidad&8] &bUso: /sendad [nick]"

formularios:
  new-form: "&f[&7A51&f] &bNuevo &eformulario &bpendiente de &e{players}"
  voy: "&f[&7A51&f] &b{user} &eestá revisando el último formulario enviado."
  telegram-channel: ""
  telegram-new-form: "Nuevo formulario pendiente de *{players}*"
  telegram-voy: "*{user}* está revisando el último formulario enviado.*{user}* está revisando el último formulario enviado."

protocol:
  name: 'Edoras 1.XX'
  version: 736
  do-not-kick: [
    736
  ]
  kick-message: "¡Versión incorrecta!.newline.Conéctate usando la versión Minecraft 1.XX"