ads-link: ""
new-forms-link: ""

publicidad:
  format: "&8[&7Publicidad&8] &b{message}"
  not-found: "&8[&7Publicidad&8] &bNo se ha encontrado ningún anuncio de {player}"
  usage: "&8[&7Publicidad&8] &bUso: /sendad [nick]"

formularios:
  new-form: "&f[&7A51&f] &bNuevo &eformulario &bpendiente de &e{players}"